### ISSUE TITLE
pnpmLockfilePath also looking for `package.json`

### ISSUE THREAD

**Issue by shailygupta** [snyk-tech-services/snyk-pnpm-github-action#10]
### Issue

 We are currently attempting to utilize this action to scan and test our pnpm project, however, we are running into the following issue:

```bash
Error: Error: Error: package.json not found at location: ./common/config/rush/package.json
```

`.github/workflows/snyk.yaml`
```yaml
name: Snyk

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  pnpm_snyk_check_dev:
    runs-on: ubuntu-latest
    name: Snyk Dev Check
    steps:
      - uses: actions/checkout@v2
      - name: Snyk API pnpm scan
        id: pnpm-scan-api-tool
        uses: snyk-tech-services/snyk-pnpm-github-action@master
        with:
          snykToken: ${{ secrets.SNYK_TOKEN}}
          pnpmLockfilePath: "./common/config/rush" 
          snykOrganization: "Engineering"
```

Directory structure:
- The lock file is in `common/config/rush` while the `package.json` is in the app's directory. 

```
.
├── README.md
├── apps
│   ├── developer-example
│   │   ├── README.md
│   │   ├── build.js
│   │   ├── cdk
│   │   │   ├── accountProps.ts
│   │   │   ├── deployDeveloperExampleStack.ts
│   │   │   └── developerExampleStack.ts
│   │   ├── cdk.json
│   │   ├── deploy.sh
│   │   ├── package.json
│   │   ├── src
│   │   │   └── handlers
│   │   │       └── helloWorldLambda.ts
│   │   ├── tests
│   │   │   ├── e2e
│   │   │   │   └── api.test.ts
│   │   │   └── unit
│   │   │       └── handlers
│   │   │           └── helloworldLambda.test.ts
│   │   └── tsconfig.json
├── common
│   ├── config
│   │   └── rush
│   │       ├── artifactory.json
│   │       ├── build-cache.json
│   │       ├── command-line.json
│   │       ├── common-versions.json
│   │       ├── experiments.json
│   │       ├── pnpm-lock.yaml
│   │      └── version-policies.json
```

### Expected

An optional variable that allows the specification of the `package.json` path as well in the action
